name: 电商系统定期代码复审
on:
  schedule:
    - cron: '0 1 * * 5'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install axios

      - name: Run monitoring script
        run: node scripts/review_monitor.js
        env:
          WECOM_WEBHOOK_URL: ${{ secrets.WECOM_WEBHOOK_WORK_URL }}
          WECOM_PIC_URL_NORMAL: ${{ secrets.WECOM_PIC_URL_REVIEW }}

      - name: Send notification on failure
        if: failure()
        run: |
          echo "任务执行失败！"