name: 电商系统异常连续监控

on:
  workflow_dispatch:  # 手动触发第一次运行

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install axios

      - name: Run monitoring script
        run: node scripts/series_error_monitor.js
        env:
          WECOM_WEBHOOK_URL: ${{ secrets.WECOM_WEBHOOK_URL }}
          WECOM_PIC_URL_NORMAL: ${{ secrets.WECOM_PIC_URL_NORMAL }}
          WECOM_PIC_URL_ERROR: ${{ secrets.WECOM_PIC_URL_ERROR }}

      - name: 自动触发下一次运行
        if: success()  # 只有成功时才触发
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ github.workflow }}.dispatches \
            -d '{"ref":"${{ github.ref }}"}'

      - name: Send notification on failure
        if: failure()
        run: |
          echo "任务执行失败！"