name: 电商系统异常准点检查通知
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true  # 设为 true 则会取消已有的运行实例

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install axios

      - name: Run monitoring script
        run: node scripts/series_error_monitor.js
        env:
          WECOM_WEBHOOK_URL: ${{ secrets.WECOM_WEBHOOK_URL }}
          WECOM_PIC_URL_NORMAL: ${{ secrets.WECOM_PIC_URL_NORMAL }}
          WECOM_PIC_URL_ERROR: ${{ secrets.WECOM_PIC_URL_ERROR }}

      - name: Send notification on failure
        if: failure()
        run: |
          echo "任务执行失败！"